export const getSkillIcon = (skillName: string): string => {
  const iconMap: Record<string, string> = {
    React: 'logos:react',
    TypeScript: 'logos:typescript-icon',
    JavaScript: 'logos:javascript',
    'JavaScript (ES6+)': 'logos:javascript',
    'Node.js': 'logos:nodejs-icon',
    'Next.js': 'logos:nextjs-icon',
    Python: 'logos:python',
    PostgreSQL: 'logos:postgresql',
    MongoDB: 'logos:mongodb-icon',
    Docker: 'logos:docker-icon',
    AWS: 'logos:aws',
    Git: 'logos:git-icon',
    HTML: 'logos:html-5',
    CSS: 'logos:css-3',
    'Tailwind CSS': 'logos:tailwindcss-icon',
    Express: 'logos:express',
    'React Native': 'logos:react',
    Redux: 'logos:redux',
    GraphQL: 'logos:graphql',
    Firebase: 'logos:firebase',
    Firestore: 'logos:firebase',
    Prisma: 'logos:prisma',
    Vercel: 'logos:vercel-icon',
    Figma: 'logos:figma',
    'REST APIs': 'mdi:api',
    Postman: 'logos:postman-icon',
    GitHub: 'logos:github-icon',
    'VS Code': 'logos:visual-studio-code',
    Linux: 'logos:linux-tux',
    'C++': 'logos:c-plusplus',
    Java: 'logos:java',
    'Material-UI': 'logos:material-ui',
    Bootstrap: 'logos:bootstrap',
    Sass: 'logos:sass',
    Webpack: 'logos:webpack',
    Vite: 'logos:vitejs',
    Yarn: 'logos:yarn',
    npm: 'logos:npm-icon',
    Eslint: 'logos:eslint',
    Prettier: 'logos:prettier',
    'GitHub Actions': 'logos:github-actions',
    Heroku: 'logos:heroku-icon',
    Netlify: 'logos:netlify',
    Redis: 'logos:redis',
    MySQL: 'logos:mysql',
    SQLite: 'logos:sqlite',
    'Socket.io': 'logos:socket-io',
    Stripe: 'logos:stripe',
    Azure: 'logos:microsoft-azure',
    DigitalOcean: 'logos:digital-ocean',
    Kubernetes: 'logos:kubernetes',
    Terraform: 'logos:terraform-icon',
    Jenkins: 'logos:jenkins',
    'CI/CD': 'mdi:pipe',
    Nginx: 'logos:nginx',
    Apache: 'logos:apache',
    Ubuntu: 'logos:ubuntu',
    MacOS: 'logos:apple',
    Windows: 'logos:microsoft-windows',
    'Framer Motion': 'simple-icons:framer',
    'Styled Components': 'simple-icons:styledcomponents',
    Storybook: 'logos:storybook-icon',
    Cypress: 'logos:cypress-icon',
    'Testing Library': 'simple-icons:testinglibrary',
    Vitest: 'logos:vitest',
    'React Query': 'logos:react-query-icon',
    Zustand: 'simple-icons:zustand',
    'React Hook Form': 'simple-icons:reacthookform',
    'React Router': 'simple-icons:reactrouter',
    'OpenAI Agents SDK': 'logos:openai-icon',
    LangChain: 'simple-icons:langchain',
    LangGraph: 'simple-icons:langgraph',
    Gemini: 'material-icon-theme:gemini-ai',
    Anthropic: 'simple-icons:anthropic',
    ElevenLabs: 'simple-icons:elevenlabs',
    NestJS: 'vscode-icons:file-type-nestjs',
    Zod: 'simple-icons:zod',
    TypeORM: 'simple-icons:typeorm',
    MikroORM: 'lucide:code',
    'Drizzle ORM': 'simple-icons:drizzle',
    OAuth2: 'simple-icons:oauth',
    JWT: 'simple-icons:jsonwebtokens',
    Web3Auth: 'simple-icons:web3auth',
    'AWS KMS': 'skill-icons:aws-light',
    'Firebase Auth': 'logos:firebase-icon',
    'Google Cloud': 'devicon:googlecloud',
    Hetzner: 'simple-icons:hetzner',
    'OAuth 2': 'tabler:brand-oauth',
    OpenSSL: 'simple-icons:openssl',
    Mocha: 'devicon:mocha',
    Chai: 'logos:chai',
    ESLint: 'vscode-icons:file-type-eslint',
    PostHog: 'logos:posthog-icon',
    EVM: 'mdi:ethereum',
    MetaMask: 'token-branded:metamask',
    Solana: 'token-branded:solana',
    Hardhat: 'devicon:hardhat',
    Solidity: 'devicon:solidity',
    PayPal: 'logos:paypal',
    'Vue.js': 'logos:vue',
    Nuxt: 'logos:nuxt-icon',
    Sentry: 'logos:sentry-icon',
    Mongoose: 'devicon:mongoose',
    Jest: 'logos:jest',
    Lodash: 'logos:lodash',
    Axios: 'logos:axios',
    'React Flow': 'simple-icons:xyflow',
    'TanStack React Query': 'logos:react-query-icon',
    'TanStack Router': 'simple-icons:tanstack',
    WebSocket: 'logos:websocket',
  };
  return iconMap[skillName] ?? 'lucide:code';
};
